### ISSUE TITLE
使用 来点七海大可爱 或者 来点七海小可爱 时报错，请问是怎么回事呢？

### ISSUE THREAD

**Issue by HorizenX1** [Soung2279/NANA7MI_REC#2]
## 日志
 INFO: Self: 11801275, Message 1834007599 from 1045925330@[群:443125748]: '来点可爱小七海'
[2021-10-07 22:05:30,676 可爱小七海] INFO: Message 1834007599 triggered send_nnmlove.
[2021-10-07 22:05:30,697 可爱小七海] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when send_nnmlove handling message 1834007599.
[2021-10-07 22:05:30,700 可爱小七海] ERROR: <ActionFailed data=None, echo={'seq': 2}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考输出'>
Traceback (most recent call last):
  File "/home/xh1045925330/genshinbot/hoshinobot/hoshinobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/home/xh1045925330/genshinbot/hoshinobot/hoshinobot/hoshino/service.py", line 224, in wrapper
    return await func(bot, event)
  File "/home/xh1045925330/genshinbot/hoshinobot/hoshinobot/hoshino/modules/NANA7MI_REC/nana7mi_record.py", line 291, in send_nnmlove
    await bot.send(ev, rec)
  File "/home/xh1045925330/genshinbot/hoshinobot/lib/python3.7/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/home/xh1045925330/genshinbot/hoshinobot/lib/python3.7/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/home/xh1045925330/genshinbot/hoshinobot/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/home/xh1045925330/genshinbot/hoshinobot/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 154, in call_action
    ResultStore.fetch(seq, self._timeout_sec))
  File "/home/xh1045925330/genshinbot/hoshinobot/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考输出'>
[2021-10-07 22:05:30,717 nonebot] INFO: Message 1834007599 is ignored: Handled by Hoshino

**Comment by 1045925330** [comment]
增强模块我是已经替换了的，语音文件路径也是对的。其他命令都能正常运行，就这两条命令会报错。

**Comment by Cathgao** [comment]
> 理论上应该是修复了不能使用的问题

还是出现这个问题
[2021-12-03 23:01:22,051 nonebot] INFO: Self: *****, Message 395516851 from ****@[群:****]: '来点不能转的'
[2021-12-03 23:01:22,052 可爱小七海] INFO: Message 395516851 triggered send_nnmsongs by PrefixTrigger.
[2021-12-03 23:01:22,114 可爱小七海] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when send_nnmsongs handling message 395516851.
[2021-12-03 23:01:22,115 可爱小七海] ERROR: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\nana7mi\nana7mi_record.py", line 147, in send_nnmsongs
    await bot.send(ev, final_send)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
[2021-12-03 23:01:22,123 nonebot] INFO: Message 395516851 is ignored: Handled by PrefixTrigger of Hoshino

**Comment by Cathgao** [comment]
其他命令也是提示发送失败，但没有详细信息
```
[2021-12-03 23:33:11,387 nonebot] INFO: Self: ****, Message 1305960118 from ****@[群:****]: '爆裂魔法'
[2021-12-03 23:33:11,390 爆裂魔法] INFO: Message 1305960118 triggered send_explosion by PrefixTrigger.
[2021-12-03 23:33:11,434 爆裂魔法] ERROR: 爆裂魔法语音发送失败。
[2021-12-03 23:33:11,435 nonebot] INFO: Message 1305960118 is ignored: Handled by PrefixTrigger of Hoshino
```

**Comment by Soung2279** [comment]
是不是语音路径不对，可以看一下语音文件的位置

**Comment by Cathgao** [comment]
> 是不是语音路径不对，可以看一下语音文件的位置

路径是对的，路径不对提示的是找不到文件

**Comment by Cathgao** [comment]
> 是不是语音路径不对，可以看一下语音文件的位置

以下是CQ的日志，看来好像是因为没有FFmpeg，我下一个试一下
```
[2021-12-05 17:05:24] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "file:///*****\\HoshinoBot\\res\\record\\nana7mi\\\u7cbe\u54c1\u5355\u66f2\\\u75c5\u5973\u5b69.mp3"}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.
[2021-12-05 17:05:24] [WARNING]: 群消息发送失败: 消息为空.
```

**Comment by Cathgao** [comment]
系统变量里添加FFmpeg解决了

**Comment by Soung2279** [comment]
好的
